const testPlayers = [
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
  {
    age: '32',
    country: 'ES',
    description: 'Jugador polivalente',
    dorsal: '9',
    expoToken: 'ExponentPushToken[rzZvAvIkzHFXoOnqWwLChF]',
    foot: 'd',
    height: '196',
    imgProfile:
      'https://firebasestorage.googleapis.com/v0/b/panamafc-81bc0.appspot.com/o/players%2F4HoudaUe0jZhA6djsKbAKBFIko82%2Fprofile.jpg?alt=media&token=ba3ab4c2-287c-43c1-94f2-69f976f986b0',
    keywords: ['', 'a', 'a.', 'a.s', 'a.so', 'a.sol', 'a.sole', 'a.soler'],
    name: 'A.Soler',
    positions: [
      { active: true, color: '#EFA11F', label: 'Delantero', shortName: 'DEL', value: 'dc' },
      { active: false, color: '#EFA11F', label: 'Extremo Izquierdo', shortName: 'EI', value: 'ei' },
      { active: true, color: '#EFA11F', label: 'Extremo derecho', shortName: 'ED', value: 'ed' },
      { active: true, color: '#489CF9', label: 'Medio centro', shortName: 'MC', value: 'mc' },
      { active: false, color: '#489CF9', label: 'Medio izquierdo', shortName: 'MI', value: 'mi' },
      { active: true, color: '#489CF9', label: 'Medio derecho', shortName: 'MD', value: 'md' },
      { active: false, color: '#8624AB', label: 'Defensa', shortName: 'DEF', value: 'df' },
      { active: true, color: '#8624AB', label: 'Lateral izquierdo', shortName: 'LI', value: 'li' },
      { active: false, color: '#8624AB', label: 'Lateral derecho', shortName: 'LD', value: 'ld' },
      { active: true, color: '#DD5E10', label: 'Portero', shortName: 'POR', value: 'pt' },
      { color: '#DB1B11', label: 'Sin asignar', shortName: 'NA', value: 'sa' },
    ],
    principalPosition: 'li',
    stats: { dribbling: 8, pass: 10, resistance: 6, shoot: 8, speed: 10, strength: 8 },
    uid: '4HoudaUe0jZhA6djsKbAKBFIko82',
    weight: '89',
  },
]
